name: Schedule Trigger for Repo1 Uat

on:
  schedule:
    - cron: '0 0 * * *'  # Adjust the schedule as needed

jobs:
  trigger:
    uses: ./.github/workflows/common-schedule.yml
    with:
      repo: 'repo1'
      environment: 'uat'
