name: Schedule Trigger for Repo2 Uat

on:
  schedule:
    - cron: '*/10 * * * *'  # Adjust the schedule as needed

jobs:
  trigger:
    uses: ./.github/workflows/common-schedule.yml
    with:
      repo: 'repo2'
      environment: 'uat'
