name: Schedule Trigger for Repo1 Uat

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 mins

jobs:
  trigger:
    uses: ./.github/workflows/common-schedule.yml
    with:
      repo: 'repo1'
      environment: 'uat'
